name: python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev --skip-lock
    - name: linting
      run: |
        pipenv run invoke lint
    - name: formatting
      run: |
        pipenv run invoke format
